import type { PluginContext, SandboxedPlugin, SandboxedRouteContext } from "emdash/plugin";
import { z } from "zod";
import { blocks, elements, type BlockInteraction, type BlockResponse } from "@emdash-cms/blocks/server";
import { altFromFilename, cdnUrl, searchAssets, type MediaAsset, type MediaJob, type MediaVersion } from "./domain";
import { callMediaProcessor } from "./processor";

interface Collection<T> { get(id:string):Promise<T|null>; put(id:string,data:T):Promise<void>; query(options?:Record<string,unknown>):Promise<{items:Array<{id:string;data:T}>;hasMore:boolean}>; count(where?:Record<string,unknown>):Promise<number> }
const store = (ctx: PluginContext) => ({ assets: ctx.storage.assets as Collection<MediaAsset>, versions: ctx.storage.versions as Collection<MediaVersion>, jobs: ctx.storage.jobs as Collection<MediaJob> });
const metadataSchema = z.object({ id:z.string().min(1), title:z.string().max(200).default(""), alt:z.string().max(500).default(""), caption:z.string().max(2000).default(""), tags:z.union([z.string(),z.array(z.string())]).default([]) });
async function saveVersion(asset:MediaAsset, ctx:PluginContext) { const s=store(ctx); const versions=await s.versions.query({where:{mediaId:asset.mediaId},limit:500}); const version=Math.max(0,...versions.items.map(x=>x.data.version))+1; const item:MediaVersion={id:crypto.randomUUID(),mediaId:asset.mediaId,version,snapshot:asset,createdAt:new Date().toISOString()}; await s.versions.put(item.id,item); }
async function dashboard(ctx:PluginContext):Promise<BlockResponse>{ const s=store(ctx); const result=await s.assets.query({orderBy:{updatedAt:"desc"},limit:100}); const assets=result.items.map(x=>x.data); return {blocks:[blocks.header("Cannelle Media"),blocks.section("DAM, métadonnées, recherche, OCR, ALT, compression, versions et CDN."),blocks.stats([{label:"Médias",value:assets.length},{label:"ALT manquants",value:assets.filter(x=>!x.alt).length},{label:"En traitement",value:assets.filter(x=>x.status==="processing").length}]),blocks.form({blockId:"search",fields:[elements.textInput("query","Recherche")],submit:{label:"Rechercher",actionId:"search"}}),blocks.table({columns:[{key:"filename",label:"Fichier"},{key:"mimeType",label:"Type"},{key:"alt",label:"ALT"},{key:"status",label:"État",format:"badge"}],rows:assets.map(x=>({...x})),pageActionId:"noop",emptyText:"Aucun média indexé"}),blocks.form({blockId:"metadata",fields:[elements.textInput("id","ID du média"),elements.textInput("title","Titre"),elements.textInput("alt","Texte alternatif"),elements.textInput("caption","Légende",{multiline:true}),elements.textInput("tags","Tags séparés par des virgules")],submit:{label:"Enregistrer",actionId:"save_metadata"}})]}; }
async function assetsRoute(routeCtx:SandboxedRouteContext,ctx:PluginContext){ const s=store(ctx); if(routeCtx.request.method.toUpperCase()==="GET"){const input=routeCtx.input as Record<string,unknown>;const result=await s.assets.query({orderBy:{updatedAt:"desc"},limit:200});const assets=result.items.map(x=>x.data);return {assets:searchAssets(assets,typeof input?.query==="string"?input.query:"")};} if(routeCtx.request.method.toUpperCase()!=="POST") throw new Response("Method not allowed",{status:405}); const parsed=metadataSchema.safeParse(routeCtx.input);if(!parsed.success)throw new Response("Invalid metadata",{status:400});const current=await s.assets.get(parsed.data.id);if(!current)throw new Response("Not found",{status:404});await saveVersion(current,ctx);const tags=Array.isArray(parsed.data.tags)?parsed.data.tags:parsed.data.tags.split(",").map(x=>x.trim()).filter(Boolean);const updated={...current,...parsed.data,tags,updatedAt:new Date().toISOString()};await s.assets.put(updated.id,updated);return {success:true,asset:updated}; }
async function jobsRoute(routeCtx:SandboxedRouteContext,ctx:PluginContext){const input=routeCtx.input as Record<string,unknown>;if(typeof input.mediaId!=="string"||!(["ocr","alt","compress"] as unknown[]).includes(input.type))throw new Response("Invalid job",{status:400});const job:MediaJob={id:crypto.randomUUID(),mediaId:input.mediaId,type:input.type as MediaJob["type"],status:"pending",createdAt:new Date().toISOString()};await store(ctx).jobs.put(job.id,job);return {success:true,job};}
async function processJob(id:string,ctx:PluginContext){const s=store(ctx),job=await s.jobs.get(id);if(!job||job.status!=="pending")return false;const asset=await s.assets.get(job.mediaId);if(!asset){await s.jobs.put(id,{...job,status:"failed",error:"Média introuvable"});return false}await s.assets.put(asset.id,{...asset,status:"processing",updatedAt:new Date().toISOString()});try{const result=await callMediaProcessor(job,asset,ctx);await saveVersion(asset,ctx);const updated:MediaAsset={...asset,alt:result.alt??asset.alt,ocrText:result.ocrText??asset.ocrText,sourceUrl:result.optimizedUrl??asset.sourceUrl,size:result.size??asset.size,status:"ready",updatedAt:new Date().toISOString()};await s.assets.put(asset.id,updated);await s.jobs.put(id,{...job,status:"done"});return true}catch(error){await s.assets.put(asset.id,{...asset,status:"failed",updatedAt:new Date().toISOString()});await s.jobs.put(id,{...job,status:"failed",error:error instanceof Error?error.message.slice(0,500):"Erreur processeur"});return false}}
async function processRoute(routeCtx:SandboxedRouteContext,ctx:PluginContext){const input=routeCtx.input as Record<string,unknown>;if(typeof input.id==="string")return{success:await processJob(input.id,ctx)};const jobs=await store(ctx).jobs.query({where:{status:"pending"},limit:10});let processed=0;for(const item of jobs.items)if(await processJob(item.id,ctx))processed++;return{success:true,processed,total:jobs.items.length};}
export default { hooks:{
	"plugin:install":async(_e,ctx)=>{await ctx.kv.set("settings:maxUploadMb",25);await ctx.kv.set("settings:allowedMimePrefixes","image/,application/pdf,video/,audio/");await ctx.kv.set("settings:autoAlt",true);await ctx.cron?.schedule("media-jobs",{schedule:"*/5 * * * *"});},
	cron:async(event,ctx)=>{if(event.name==="media-jobs")await processRoute({input:{},request:{url:"https://internal/media-jobs",method:"POST",headers:{}}},ctx);},
	"media:beforeUpload":async(event,ctx)=>{const max=(await ctx.kv.get<number>("settings:maxUploadMb"))??25;const allowed=((await ctx.kv.get<string>("settings:allowedMimePrefixes"))??"image/,application/pdf").split(",").map(x=>x.trim());if(event.file.size>max*1024*1024)throw new Error(`Fichier supérieur à ${max} Mo`);if(!allowed.some(prefix=>event.file.type.startsWith(prefix)))throw new Error("Type de fichier non autorisé");},
	"media:afterUpload":async(event,ctx)=>{const now=new Date().toISOString();const autoAlt=(await ctx.kv.get<boolean>("settings:autoAlt"))!==false;const asset:MediaAsset={id:event.media.id,mediaId:event.media.id,filename:event.media.filename,mimeType:event.media.mimeType,size:event.media.size,sourceUrl:event.media.url,title:altFromFilename(event.media.filename),alt:autoAlt?altFromFilename(event.media.filename):"",caption:"",tags:[],ocrText:"",status:"ready",createdAt:now,updatedAt:now};await store(ctx).assets.put(asset.id,asset);await saveVersion(asset,ctx);},
},routes:{assets:{permission:"plugins:read",input:z.unknown(),handler:assetsRoute},jobs:{input:z.unknown(),handler:jobsRoute},process:{input:z.unknown(),handler:processRoute},cdn:{permission:"plugins:read",input:z.unknown(),handler:async(routeCtx,ctx)=>{const input=routeCtx.input as Record<string,unknown>;if(typeof input.id!=="string")throw new Response("Invalid id",{status:400});const asset=await store(ctx).assets.get(input.id);if(!asset)throw new Response("Not found",{status:404});return {url:cdnUrl(asset.sourceUrl,(await ctx.kv.get<string>("settings:cdnBaseUrl"))??"")};}},admin:{input:z.unknown(),handler:async(routeCtx,ctx)=>{const interaction=routeCtx.input as BlockInteraction;if(interaction?.type==="form_submit"&&interaction.action_id==="save_metadata"){await assetsRoute({...routeCtx,input:interaction.values,request:{...routeCtx.request,method:"POST"}},ctx);return {...await dashboard(ctx),toast:{message:"Métadonnées enregistrées.",type:"success"}};}return dashboard(ctx);}}}} satisfies SandboxedPlugin;
